<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <script src="../js/Test.js"></script>
    <title>Document</title>
</head>
<body>

<input onclick=doTheTest() type="submit" value="Click to start the test">
<p id="result">Here will be your answers</p>
<p id="a1"></p>
<p id="a2"></p>
<p id="a3"></p>
<p id="a4"></p>
<p id="a5"></p>
<p id="rate"></p>

</body>
</html>